# Generated by Django 5.0.1 on 2024-06-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_alter_contact_us_email_alter_contact_us_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactt_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='contact_us',
        ),
    ]
