# Generated by Django 5.0.1 on 2024-06-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_contactt_us_delete_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactt_us',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
